# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a0vSjKV9kKp8KsZ24JYPWemfbgqxIvYm
"""

#Circle Involute
from sympy import symbols, cos, sin, pi
from sympy.plotting import plot_parametric

a = 2
t = symbols('t')
x = a * (cos (t))
y = a * (sin (t))

xi = a * (cos(t) + t * sin(t))
yi = a * (sin(t) - t * cos(t))

#plot_parametric((x, y, (t, 0, 6*pi)))
plot_parametric(
    (x, y, (t,2 , 6* pi)),
    (xi, yi, (t, 0 , 2* pi))
    #show=True, title='Curvas Paramétricas'
)

#Grafica 2

r = 1/3
t = symbols('t')

x = r * (2 * cos(t) - cos(2 * t))
y = r * (-3 * sin(t) - sin(-3 * t))

xi = 1/9 * (2 * cos(t) + cos(2 * t))
yi = 1/9 * (2 * sin(t) - sin(2 * t))

plot_parametric(
    (x, y, (t, 0, 2* pi)),
    (xi, yi, (t, 0, 3 * pi))
)

#Grafica 3
r = 0.125
t = symbols('t')

x = r * (3 * cos(t) - cos (3 * t))
y = r * (3 * sin (t) + sin (3* t))

xi = cos (t)**3
yi = sin (t)**3

#plot_parametric((x, y, (t, 0, 4*pi)))
plot_parametric(
    (x, y, (t, 0, 2* pi)),
    (xi, yi, (t, 0, 3 * pi))
)

#4Cardioid
r = 3
t = symbols('t')

x = r * (1 + cos(t)) * cos(t)
y = r * (1 + cos(t)) * sin(t)

xi = 2 * r + 3 * r * (cos(t) * (1 - cos(t)))
yi = 3 * r * (sin(t) * (1 - cos(t)))

plot_parametric(
    (x, y, (t, -2 * pi, 2 * pi)),
    (xi, yi, (t, -2 * pi, 2 * pi)),
    show=True
)

#Grafica 5

r = 3
t = symbols('t')

x = r * (t + sin(t))
y = r * (3 + cos(t))

xi=	r * (t - sin(t))
yi=	r * (1 - cos(t))

plot_parametric(
    (x, y, (t, -2 * pi, 2 * pi)),
    (xi, yi, (t, -2 * pi, 2 * pi)),
    show=True
)